version: '3'
services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:latest
    container_name: enshrouded
    network_mode: "host"
    ports:
      - "15636:15636/tcp"
      - "15636:15636/udp"
      - "15637:15637/tcp"
      - "15637:15637/udp"
      - "27015:27015/tcp"
      - "27015:27015/udp"
    environment:
      - SERVER_NAME=channel27
      - SERVER_PASSWORD=groovyfunky
      - GAME_PORT=15636
      - QUERY_PORT=15637
      - SERVER_SLOTS=4
      #- SERVER_IP=35.212.241.134
      #- SERVER_IP=127.0.0.1
      - SERVER_IP=0.0.0.0
    volumes:
      - enshrouded-persistent-data:/home/steam/enshrouded/savegame

volumes:
  enshrouded-persistent-data:
