services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    environment:
      - SUPERVISOR_HTTP=true
      - STATUS_HTTP=true
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
      - "80:80/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m
