services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    container_name: game-server
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
      - "80:80/tcp"
    env_file:
      - $HOME/igetit41-docker-game-server/game-server/valheim/valheim.env
    restart: always
    stop_grace_period: 2m
